# Generated by Django 2.0.5 on 2018-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
