# Generated by Django 2.0.5 on 2018-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_choice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
