# docker-compose for local development
# run with nginx

version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build:
      context: app
      dockerfile: Dockerfile
    command: bash -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - static:/www/static
    links:
      - postgres

  nginx:
    build: nginx
    ports:
      - "8000:80"  # HOST:CONTAINER
    volumes_from:
      - web
    links:
      - web

volumes:
  pgdata:
  static:
